// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uabhicleiumptashiarr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhYmhpY2xlaXVtcHRhc2hpYXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDIxODcsImV4cCI6MjA2MjgxODE4N30.hPGz7n7vLXD62iKSYK0482jUFaTGtCFWnY4glUhsn_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);